// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */

import {faker} from "@faker-js/faker";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    InvalidateOptions,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";
import {useMutation, useQuery} from "@tanstack/react-query";
import type {RequestHandlerOptions} from "msw";

import {HttpResponse, http} from "msw";
import type {
    BatchDeleteNonConformitiesRequest,
    BatchSetWaiverRequest,
    GetAuditRuleResponse,
    ListAuditNonConformitiesResponse,
    ListAuditRulesResponse,
    ScanAuditRuleResponse,
    SetWaiverRequest,
} from "../model";

export type listAuditRulesResponse200TextPlain = {
    data: ListAuditRulesResponse;
    status: 200;
};

export type listAuditRulesResponse200ApplicationJson = {
    data: ListAuditRulesResponse;
    status: 200;
};

export type listAuditRulesResponse200TextJson = {
    data: ListAuditRulesResponse;
    status: 200;
};

export type listAuditRulesResponseSuccess = (
    | listAuditRulesResponse200TextPlain
    | listAuditRulesResponse200ApplicationJson
    | listAuditRulesResponse200TextJson
    ) & {
    headers: Headers;
};

export type listAuditRulesResponse = listAuditRulesResponseSuccess;

export const getListAuditRulesUrl = () => {
    return `/api/audits/rules`;
};

export const listAuditRules = async (
    options?: RequestInit,
): Promise<listAuditRulesResponse> => {
    const res = await fetch(getListAuditRulesUrl(), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: listAuditRulesResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as listAuditRulesResponse;
};

export const getListAuditRulesQueryKey = () => {
    return ["api", "audits", "rules"] as const;
};

export const getListAuditRulesQueryOptions = <
    TData = Awaited<ReturnType<typeof listAuditRules>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof listAuditRules>>, TError, TData>
    >;
    fetch?: RequestInit;
}) => {
    const {query: queryOptions, fetch: fetchOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListAuditRulesQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAuditRules>>> = ({
                                                                                    signal,
                                                                                }) => listAuditRules({signal, ...fetchOptions});

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof listAuditRules>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAuditRulesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listAuditRules>>
>;
export type ListAuditRulesQueryError = unknown;

export function useListAuditRules<
    TData = Awaited<ReturnType<typeof listAuditRules>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof listAuditRules>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAuditRules>>,
                    TError,
                    Awaited<ReturnType<typeof listAuditRules>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAuditRules<
    TData = Awaited<ReturnType<typeof listAuditRules>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof listAuditRules>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAuditRules>>,
                    TError,
                    Awaited<ReturnType<typeof listAuditRules>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAuditRules<
    TData = Awaited<ReturnType<typeof listAuditRules>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof listAuditRules>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListAuditRules<
    TData = Awaited<ReturnType<typeof listAuditRules>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof listAuditRules>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListAuditRulesQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return {...query, queryKey: queryOptions.queryKey};
}

export const invalidateListAuditRules = async (
    queryClient: QueryClient,
    options?: InvalidateOptions,
): Promise<QueryClient> => {
    await queryClient.invalidateQueries(
        {queryKey: getListAuditRulesQueryKey()},
        options,
    );

    return queryClient;
};

export type getAuditRuleResponse200TextPlain = {
    data: GetAuditRuleResponse;
    status: 200;
};

export type getAuditRuleResponse200ApplicationJson = {
    data: GetAuditRuleResponse;
    status: 200;
};

export type getAuditRuleResponse200TextJson = {
    data: GetAuditRuleResponse;
    status: 200;
};

export type getAuditRuleResponseSuccess = (
    | getAuditRuleResponse200TextPlain
    | getAuditRuleResponse200ApplicationJson
    | getAuditRuleResponse200TextJson
    ) & {
    headers: Headers;
};

export type getAuditRuleResponse = getAuditRuleResponseSuccess;

export const getGetAuditRuleUrl = (id: number) => {
    return `/api/audits/rules/${id}`;
};

export const getAuditRule = async (
    id: number,
    options?: RequestInit,
): Promise<getAuditRuleResponse> => {
    const res = await fetch(getGetAuditRuleUrl(id), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getAuditRuleResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as getAuditRuleResponse;
};

export const getGetAuditRuleQueryKey = (id: number) => {
    return ["api", "audits", "rules", id] as const;
};

export const getGetAuditRuleQueryOptions = <
    TData = Awaited<ReturnType<typeof getAuditRule>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAuditRule>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
) => {
    const {query: queryOptions, fetch: fetchOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAuditRuleQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuditRule>>> = ({
                                                                                  signal,
                                                                              }) => getAuditRule(id, {signal, ...fetchOptions});

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getAuditRule>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuditRuleQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAuditRule>>
>;
export type GetAuditRuleQueryError = unknown;

export function useGetAuditRule<
    TData = Awaited<ReturnType<typeof getAuditRule>>,
    TError = unknown,
>(
    id: number,
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAuditRule>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAuditRule>>,
                    TError,
                    Awaited<ReturnType<typeof getAuditRule>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuditRule<
    TData = Awaited<ReturnType<typeof getAuditRule>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAuditRule>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAuditRule>>,
                    TError,
                    Awaited<ReturnType<typeof getAuditRule>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuditRule<
    TData = Awaited<ReturnType<typeof getAuditRule>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAuditRule>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAuditRule<
    TData = Awaited<ReturnType<typeof getAuditRule>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getAuditRule>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAuditRuleQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return {...query, queryKey: queryOptions.queryKey};
}

export const invalidateGetAuditRule = async (
    queryClient: QueryClient,
    id: number,
    options?: InvalidateOptions,
): Promise<QueryClient> => {
    await queryClient.invalidateQueries(
        {queryKey: getGetAuditRuleQueryKey(id)},
        options,
    );

    return queryClient;
};

export type scanAuditRuleResponse200TextPlain = {
    data: ScanAuditRuleResponse;
    status: 200;
};

export type scanAuditRuleResponse200ApplicationJson = {
    data: ScanAuditRuleResponse;
    status: 200;
};

export type scanAuditRuleResponse200TextJson = {
    data: ScanAuditRuleResponse;
    status: 200;
};

export type scanAuditRuleResponseSuccess = (
    | scanAuditRuleResponse200TextPlain
    | scanAuditRuleResponse200ApplicationJson
    | scanAuditRuleResponse200TextJson
    ) & {
    headers: Headers;
};

export type scanAuditRuleResponse = scanAuditRuleResponseSuccess;

export const getScanAuditRuleUrl = (id: number) => {
    return `/api/audits/rules/${id}/scan`;
};

export const scanAuditRule = async (
    id: number,
    options?: RequestInit,
): Promise<scanAuditRuleResponse> => {
    const res = await fetch(getScanAuditRuleUrl(id), {
        ...options,
        method: "POST",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: scanAuditRuleResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as scanAuditRuleResponse;
};

export const getScanAuditRuleMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof scanAuditRule>>,
        TError,
        { id: number },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof scanAuditRule>>,
    TError,
    { id: number },
    TContext
> => {
    const mutationKey = ["scanAuditRule"];
    const {mutation: mutationOptions, fetch: fetchOptions} = options
        ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, fetch: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof scanAuditRule>>,
        { id: number }
    > = (props) => {
        const {id} = props ?? {};

        return scanAuditRule(id, fetchOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type ScanAuditRuleMutationResult = NonNullable<
    Awaited<ReturnType<typeof scanAuditRule>>
>;

export type ScanAuditRuleMutationError = unknown;

export const useScanAuditRule = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof scanAuditRule>>,
            TError,
            { id: number },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof scanAuditRule>>,
    TError,
    { id: number },
    TContext
> => {
    return useMutation(getScanAuditRuleMutationOptions(options), queryClient);
};
export type listAuditNonConformitiesResponse200TextPlain = {
    data: ListAuditNonConformitiesResponse;
    status: 200;
};

export type listAuditNonConformitiesResponse200ApplicationJson = {
    data: ListAuditNonConformitiesResponse;
    status: 200;
};

export type listAuditNonConformitiesResponse200TextJson = {
    data: ListAuditNonConformitiesResponse;
    status: 200;
};

export type listAuditNonConformitiesResponseSuccess = (
    | listAuditNonConformitiesResponse200TextPlain
    | listAuditNonConformitiesResponse200ApplicationJson
    | listAuditNonConformitiesResponse200TextJson
    ) & {
    headers: Headers;
};

export type listAuditNonConformitiesResponse =
    listAuditNonConformitiesResponseSuccess;

export const getListAuditNonConformitiesUrl = (id: number) => {
    return `/api/audits/rules/${id}/non-conformities`;
};

export const listAuditNonConformities = async (
    id: number,
    options?: RequestInit,
): Promise<listAuditNonConformitiesResponse> => {
    const res = await fetch(getListAuditNonConformitiesUrl(id), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: listAuditNonConformitiesResponse["data"] = body
        ? JSON.parse(body)
        : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as listAuditNonConformitiesResponse;
};

export const getListAuditNonConformitiesQueryKey = (id: number) => {
    return ["api", "audits", "rules", id, "non-conformities"] as const;
};

export const getListAuditNonConformitiesQueryOptions = <
    TData = Awaited<ReturnType<typeof listAuditNonConformities>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAuditNonConformities>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
) => {
    const {query: queryOptions, fetch: fetchOptions} = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListAuditNonConformitiesQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listAuditNonConformities>>
    > = ({signal}) => listAuditNonConformities(id, {signal, ...fetchOptions});

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof listAuditNonConformities>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAuditNonConformitiesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listAuditNonConformities>>
>;
export type ListAuditNonConformitiesQueryError = unknown;

export function useListAuditNonConformities<
    TData = Awaited<ReturnType<typeof listAuditNonConformities>>,
    TError = unknown,
>(
    id: number,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAuditNonConformities>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAuditNonConformities>>,
                    TError,
                    Awaited<ReturnType<typeof listAuditNonConformities>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAuditNonConformities<
    TData = Awaited<ReturnType<typeof listAuditNonConformities>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAuditNonConformities>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAuditNonConformities>>,
                    TError,
                    Awaited<ReturnType<typeof listAuditNonConformities>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAuditNonConformities<
    TData = Awaited<ReturnType<typeof listAuditNonConformities>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAuditNonConformities>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListAuditNonConformities<
    TData = Awaited<ReturnType<typeof listAuditNonConformities>>,
    TError = unknown,
>(
    id: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAuditNonConformities>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListAuditNonConformitiesQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return {...query, queryKey: queryOptions.queryKey};
}

export const invalidateListAuditNonConformities = async (
    queryClient: QueryClient,
    id: number,
    options?: InvalidateOptions,
): Promise<QueryClient> => {
    await queryClient.invalidateQueries(
        {queryKey: getListAuditNonConformitiesQueryKey(id)},
        options,
    );

    return queryClient;
};

export type setAuditWaiverResponse200 = {
    data: void;
    status: 200;
};

export type setAuditWaiverResponseSuccess = setAuditWaiverResponse200 & {
    headers: Headers;
};

export type setAuditWaiverResponse = setAuditWaiverResponseSuccess;

export const getSetAuditWaiverUrl = (id: number) => {
    return `/api/audits/non-conformities/${id}/waiver`;
};

export const setAuditWaiver = async (
    id: number,
    setWaiverRequest: SetWaiverRequest,
    options?: RequestInit,
): Promise<setAuditWaiverResponse> => {
    const res = await fetch(getSetAuditWaiverUrl(id), {
        ...options,
        method: "POST",
        headers: {"Content-Type": "application/json", ...options?.headers},
        body: JSON.stringify(setWaiverRequest),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: setAuditWaiverResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as setAuditWaiverResponse;
};

export const getSetAuditWaiverMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof setAuditWaiver>>,
        TError,
        { id: number; data: SetWaiverRequest },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof setAuditWaiver>>,
    TError,
    { id: number; data: SetWaiverRequest },
    TContext
> => {
    const mutationKey = ["setAuditWaiver"];
    const {mutation: mutationOptions, fetch: fetchOptions} = options
        ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, fetch: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof setAuditWaiver>>,
        { id: number; data: SetWaiverRequest }
    > = (props) => {
        const {id, data} = props ?? {};

        return setAuditWaiver(id, data, fetchOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type SetAuditWaiverMutationResult = NonNullable<
    Awaited<ReturnType<typeof setAuditWaiver>>
>;
export type SetAuditWaiverMutationBody = SetWaiverRequest;
export type SetAuditWaiverMutationError = unknown;

export const useSetAuditWaiver = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof setAuditWaiver>>,
            TError,
            { id: number; data: SetWaiverRequest },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof setAuditWaiver>>,
    TError,
    { id: number; data: SetWaiverRequest },
    TContext
> => {
    return useMutation(getSetAuditWaiverMutationOptions(options), queryClient);
};
export type deleteAuditNonConformityResponse200 = {
    data: void;
    status: 200;
};

export type deleteAuditNonConformityResponseSuccess =
    deleteAuditNonConformityResponse200 & {
    headers: Headers;
};

export type deleteAuditNonConformityResponse =
    deleteAuditNonConformityResponseSuccess;

export const getDeleteAuditNonConformityUrl = (id: number) => {
    return `/api/audits/non-conformities/${id}`;
};

export const deleteAuditNonConformity = async (
    id: number,
    options?: RequestInit,
): Promise<deleteAuditNonConformityResponse> => {
    const res = await fetch(getDeleteAuditNonConformityUrl(id), {
        ...options,
        method: "DELETE",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deleteAuditNonConformityResponse["data"] = body
        ? JSON.parse(body)
        : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as deleteAuditNonConformityResponse;
};

export const getDeleteAuditNonConformityMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteAuditNonConformity>>,
        TError,
        { id: number },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuditNonConformity>>,
    TError,
    { id: number },
    TContext
> => {
    const mutationKey = ["deleteAuditNonConformity"];
    const {mutation: mutationOptions, fetch: fetchOptions} = options
        ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, fetch: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteAuditNonConformity>>,
        { id: number }
    > = (props) => {
        const {id} = props ?? {};

        return deleteAuditNonConformity(id, fetchOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type DeleteAuditNonConformityMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteAuditNonConformity>>
>;

export type DeleteAuditNonConformityMutationError = unknown;

export const useDeleteAuditNonConformity = <
    TError = unknown,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteAuditNonConformity>>,
            TError,
            { id: number },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof deleteAuditNonConformity>>,
    TError,
    { id: number },
    TContext
> => {
    return useMutation(
        getDeleteAuditNonConformityMutationOptions(options),
        queryClient,
    );
};
export type batchSetAuditWaiverResponse200 = {
    data: void;
    status: 200;
};

export type batchSetAuditWaiverResponseSuccess =
    batchSetAuditWaiverResponse200 & {
    headers: Headers;
};

export type batchSetAuditWaiverResponse = batchSetAuditWaiverResponseSuccess;

export const getBatchSetAuditWaiverUrl = () => {
    return `/api/audits/non-conformities/waiver/batch`;
};

export const batchSetAuditWaiver = async (
    batchSetWaiverRequest: BatchSetWaiverRequest,
    options?: RequestInit,
): Promise<batchSetAuditWaiverResponse> => {
    const res = await fetch(getBatchSetAuditWaiverUrl(), {
        ...options,
        method: "POST",
        headers: {"Content-Type": "application/json", ...options?.headers},
        body: JSON.stringify(batchSetWaiverRequest),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: batchSetAuditWaiverResponse["data"] = body
        ? JSON.parse(body)
        : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as batchSetAuditWaiverResponse;
};

export const getBatchSetAuditWaiverMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof batchSetAuditWaiver>>,
        TError,
        { data: BatchSetWaiverRequest },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof batchSetAuditWaiver>>,
    TError,
    { data: BatchSetWaiverRequest },
    TContext
> => {
    const mutationKey = ["batchSetAuditWaiver"];
    const {mutation: mutationOptions, fetch: fetchOptions} = options
        ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, fetch: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof batchSetAuditWaiver>>,
        { data: BatchSetWaiverRequest }
    > = (props) => {
        const {data} = props ?? {};

        return batchSetAuditWaiver(data, fetchOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type BatchSetAuditWaiverMutationResult = NonNullable<
    Awaited<ReturnType<typeof batchSetAuditWaiver>>
>;
export type BatchSetAuditWaiverMutationBody = BatchSetWaiverRequest;
export type BatchSetAuditWaiverMutationError = unknown;

export const useBatchSetAuditWaiver = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof batchSetAuditWaiver>>,
            TError,
            { data: BatchSetWaiverRequest },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof batchSetAuditWaiver>>,
    TError,
    { data: BatchSetWaiverRequest },
    TContext
> => {
    return useMutation(
        getBatchSetAuditWaiverMutationOptions(options),
        queryClient,
    );
};
export type batchDeleteAuditNonConformitiesResponse200 = {
    data: void;
    status: 200;
};

export type batchDeleteAuditNonConformitiesResponseSuccess =
    batchDeleteAuditNonConformitiesResponse200 & {
    headers: Headers;
};

export type batchDeleteAuditNonConformitiesResponse =
    batchDeleteAuditNonConformitiesResponseSuccess;

export const getBatchDeleteAuditNonConformitiesUrl = () => {
    return `/api/audits/non-conformities/batch-delete`;
};

export const batchDeleteAuditNonConformities = async (
    batchDeleteNonConformitiesRequest: BatchDeleteNonConformitiesRequest,
    options?: RequestInit,
): Promise<batchDeleteAuditNonConformitiesResponse> => {
    const res = await fetch(getBatchDeleteAuditNonConformitiesUrl(), {
        ...options,
        method: "POST",
        headers: {"Content-Type": "application/json", ...options?.headers},
        body: JSON.stringify(batchDeleteNonConformitiesRequest),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: batchDeleteAuditNonConformitiesResponse["data"] = body
        ? JSON.parse(body)
        : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as batchDeleteAuditNonConformitiesResponse;
};

export const getBatchDeleteAuditNonConformitiesMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof batchDeleteAuditNonConformities>>,
        TError,
        { data: BatchDeleteNonConformitiesRequest },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof batchDeleteAuditNonConformities>>,
    TError,
    { data: BatchDeleteNonConformitiesRequest },
    TContext
> => {
    const mutationKey = ["batchDeleteAuditNonConformities"];
    const {mutation: mutationOptions, fetch: fetchOptions} = options
        ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, fetch: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof batchDeleteAuditNonConformities>>,
        { data: BatchDeleteNonConformitiesRequest }
    > = (props) => {
        const {data} = props ?? {};

        return batchDeleteAuditNonConformities(data, fetchOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type BatchDeleteAuditNonConformitiesMutationResult = NonNullable<
    Awaited<ReturnType<typeof batchDeleteAuditNonConformities>>
>;
export type BatchDeleteAuditNonConformitiesMutationBody =
    BatchDeleteNonConformitiesRequest;
export type BatchDeleteAuditNonConformitiesMutationError = unknown;

export const useBatchDeleteAuditNonConformities = <
    TError = unknown,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof batchDeleteAuditNonConformities>>,
            TError,
            { data: BatchDeleteNonConformitiesRequest },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof batchDeleteAuditNonConformities>>,
    TError,
    { data: BatchDeleteNonConformitiesRequest },
    TContext
> => {
    return useMutation(
        getBatchDeleteAuditNonConformitiesMutationOptions(options),
        queryClient,
    );
};

export const getListAuditRulesResponseMock = (
    overrideResponse: Partial<Extract<ListAuditRulesResponse, object>> = {},
): ListAuditRulesResponse =>
    faker.helpers.arrayElement([
        {
            rules: Array.from(
                {length: faker.number.int({min: 1, max: 10})},
                (_, i) => i + 1,
            ).map(() => ({
                id: faker.number.int(),
                name: faker.string.alpha({length: {min: 10, max: 20}}),
                icon: faker.string.alpha({length: {min: 10, max: 20}}),
                description: faker.string.alpha({length: {min: 10, max: 20}}),
                nonConformityCount: faker.number.int(),
            })),
            ...overrideResponse,
        },
        {
            rules: Array.from(
                {length: faker.number.int({min: 1, max: 10})},
                (_, i) => i + 1,
            ).map(() => ({
                id: faker.number.int(),
                name: faker.string.alpha({length: {min: 10, max: 20}}),
                icon: faker.string.alpha({length: {min: 10, max: 20}}),
                description: faker.string.alpha({length: {min: 10, max: 20}}),
                nonConformityCount: faker.number.int(),
            })),
            ...overrideResponse,
        },
        {
            rules: Array.from(
                {length: faker.number.int({min: 1, max: 10})},
                (_, i) => i + 1,
            ).map(() => ({
                id: faker.number.int(),
                name: faker.string.alpha({length: {min: 10, max: 20}}),
                icon: faker.string.alpha({length: {min: 10, max: 20}}),
                description: faker.string.alpha({length: {min: 10, max: 20}}),
                nonConformityCount: faker.number.int(),
            })),
            ...overrideResponse,
        },
    ]);

export const getGetAuditRuleResponseMock = (
    overrideResponse: Partial<Extract<GetAuditRuleResponse, object>> = {},
): GetAuditRuleResponse =>
    faker.helpers.arrayElement([
        {
            rule: {
                id: faker.number.int(),
                name: faker.string.alpha({length: {min: 10, max: 20}}),
                icon: faker.string.alpha({length: {min: 10, max: 20}}),
                description: faker.string.alpha({length: {min: 10, max: 20}}),
                nonConformityCount: faker.number.int(),
            },
            ...overrideResponse,
        },
        {
            rule: {
                id: faker.number.int(),
                name: faker.string.alpha({length: {min: 10, max: 20}}),
                icon: faker.string.alpha({length: {min: 10, max: 20}}),
                description: faker.string.alpha({length: {min: 10, max: 20}}),
                nonConformityCount: faker.number.int(),
            },
            ...overrideResponse,
        },
        {
            rule: {
                id: faker.number.int(),
                name: faker.string.alpha({length: {min: 10, max: 20}}),
                icon: faker.string.alpha({length: {min: 10, max: 20}}),
                description: faker.string.alpha({length: {min: 10, max: 20}}),
                nonConformityCount: faker.number.int(),
            },
            ...overrideResponse,
        },
    ]);

export const getScanAuditRuleResponseMock = (
    overrideResponse: Partial<Extract<ScanAuditRuleResponse, object>> = {},
): ScanAuditRuleResponse =>
    faker.helpers.arrayElement([
        {nonConformitiesCreated: faker.number.int(), ...overrideResponse},
        {nonConformitiesCreated: faker.number.int(), ...overrideResponse},
        {nonConformitiesCreated: faker.number.int(), ...overrideResponse},
    ]);

export const getListAuditNonConformitiesResponseMock = (
    overrideResponse: Partial<
        Extract<ListAuditNonConformitiesResponse, object>
    > = {},
): ListAuditNonConformitiesResponse =>
    faker.helpers.arrayElement([
        {
            nonConformities: Array.from(
                {length: faker.number.int({min: 1, max: 10})},
                (_, i) => i + 1,
            ).map(() => ({
                id: faker.number.int(),
                songId: faker.number.int(),
                song: {
                    id: faker.number.int(),
                    cover: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([faker.number.int(), null]),
                        null,
                    ]),
                    title: faker.string.alpha({length: {min: 10, max: 20}}),
                    artists: Array.from(
                        {length: faker.number.int({min: 1, max: 10})},
                        (_, i) => i + 1,
                    ).map(() => ({
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    })),
                    album: {
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    },
                    genres: Array.from(
                        {length: faker.number.int({min: 1, max: 10})},
                        (_, i) => i + 1,
                    ).map(() => ({
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    })),
                    year: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([faker.number.int(), null]),
                        null,
                    ]),
                    duration: faker.string.alpha({length: {min: 10, max: 20}}),
                    isFavorite: faker.datatype.boolean(),
                    isExplicit: faker.datatype.boolean(),
                    createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
                    addedAt: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([
                            faker.date.past().toISOString().slice(0, 19) + "Z",
                            null,
                        ]),
                        undefined,
                    ]),
                },
                hasWaiver: faker.datatype.boolean(),
                waiverReason: faker.helpers.arrayElement([
                    faker.helpers.arrayElement([
                        faker.string.alpha({length: {min: 10, max: 20}}),
                        null,
                    ]),
                    undefined,
                ]),
                createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
            })),
            ...overrideResponse,
        },
        {
            nonConformities: Array.from(
                {length: faker.number.int({min: 1, max: 10})},
                (_, i) => i + 1,
            ).map(() => ({
                id: faker.number.int(),
                songId: faker.number.int(),
                song: {
                    id: faker.number.int(),
                    cover: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([faker.number.int(), null]),
                        null,
                    ]),
                    title: faker.string.alpha({length: {min: 10, max: 20}}),
                    artists: Array.from(
                        {length: faker.number.int({min: 1, max: 10})},
                        (_, i) => i + 1,
                    ).map(() => ({
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    })),
                    album: {
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    },
                    genres: Array.from(
                        {length: faker.number.int({min: 1, max: 10})},
                        (_, i) => i + 1,
                    ).map(() => ({
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    })),
                    year: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([faker.number.int(), null]),
                        null,
                    ]),
                    duration: faker.string.alpha({length: {min: 10, max: 20}}),
                    isFavorite: faker.datatype.boolean(),
                    isExplicit: faker.datatype.boolean(),
                    createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
                    addedAt: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([
                            faker.date.past().toISOString().slice(0, 19) + "Z",
                            null,
                        ]),
                        undefined,
                    ]),
                },
                hasWaiver: faker.datatype.boolean(),
                waiverReason: faker.helpers.arrayElement([
                    faker.helpers.arrayElement([
                        faker.string.alpha({length: {min: 10, max: 20}}),
                        null,
                    ]),
                    undefined,
                ]),
                createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
            })),
            ...overrideResponse,
        },
        {
            nonConformities: Array.from(
                {length: faker.number.int({min: 1, max: 10})},
                (_, i) => i + 1,
            ).map(() => ({
                id: faker.number.int(),
                songId: faker.number.int(),
                song: {
                    id: faker.number.int(),
                    cover: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([faker.number.int(), null]),
                        null,
                    ]),
                    title: faker.string.alpha({length: {min: 10, max: 20}}),
                    artists: Array.from(
                        {length: faker.number.int({min: 1, max: 10})},
                        (_, i) => i + 1,
                    ).map(() => ({
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    })),
                    album: {
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    },
                    genres: Array.from(
                        {length: faker.number.int({min: 1, max: 10})},
                        (_, i) => i + 1,
                    ).map(() => ({
                        id: faker.number.int(),
                        name: faker.string.alpha({length: {min: 10, max: 20}}),
                    })),
                    year: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([faker.number.int(), null]),
                        null,
                    ]),
                    duration: faker.string.alpha({length: {min: 10, max: 20}}),
                    isFavorite: faker.datatype.boolean(),
                    isExplicit: faker.datatype.boolean(),
                    createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
                    addedAt: faker.helpers.arrayElement([
                        faker.helpers.arrayElement([
                            faker.date.past().toISOString().slice(0, 19) + "Z",
                            null,
                        ]),
                        undefined,
                    ]),
                },
                hasWaiver: faker.datatype.boolean(),
                waiverReason: faker.helpers.arrayElement([
                    faker.helpers.arrayElement([
                        faker.string.alpha({length: {min: 10, max: 20}}),
                        null,
                    ]),
                    undefined,
                ]),
                createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
            })),
            ...overrideResponse,
        },
    ]);

export const getListAuditRulesMockHandler = (
    overrideResponse?:
        | ListAuditRulesResponse
        | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<ListAuditRulesResponse> | ListAuditRulesResponse),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/audits/rules",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getListAuditRulesResponseMock(),
                {status: 200},
            );
        },
        options,
    );
};

export const getGetAuditRuleMockHandler = (
    overrideResponse?:
        | GetAuditRuleResponse
        | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<GetAuditRuleResponse> | GetAuditRuleResponse),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/audits/rules/:id",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetAuditRuleResponseMock(),
                {status: 200},
            );
        },
        options,
    );
};

export const getScanAuditRuleMockHandler = (
    overrideResponse?:
        | ScanAuditRuleResponse
        | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
    ) => Promise<ScanAuditRuleResponse> | ScanAuditRuleResponse),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/audits/rules/:id/scan",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getScanAuditRuleResponseMock(),
                {status: 200},
            );
        },
        options,
    );
};

export const getListAuditNonConformitiesMockHandler = (
    overrideResponse?:
        | ListAuditNonConformitiesResponse
        | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) =>
        | Promise<ListAuditNonConformitiesResponse>
        | ListAuditNonConformitiesResponse),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/audits/rules/:id/non-conformities",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getListAuditNonConformitiesResponseMock(),
                {status: 200},
            );
        },
        options,
    );
};

export const getSetAuditWaiverMockHandler = (
    overrideResponse?:
        | void
        | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
    ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/audits/non-conformities/:id/waiver",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            if (typeof overrideResponse === "function") {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options,
    );
};

export const getDeleteAuditNonConformityMockHandler = (
    overrideResponse?:
        | void
        | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
    ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.delete(
        "*/audits/non-conformities/:id",
        async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
            if (typeof overrideResponse === "function") {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options,
    );
};

export const getBatchSetAuditWaiverMockHandler = (
    overrideResponse?:
        | void
        | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
    ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/audits/non-conformities/waiver/batch",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            if (typeof overrideResponse === "function") {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options,
    );
};

export const getBatchDeleteAuditNonConformitiesMockHandler = (
    overrideResponse?:
        | void
        | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
    ) => Promise<void> | void),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/audits/non-conformities/batch-delete",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            if (typeof overrideResponse === "function") {
                await overrideResponse(info);
            }

            return new HttpResponse(null, {status: 200});
        },
        options,
    );
};
export const getAuditsMock = () => [
    getListAuditRulesMockHandler(),
    getGetAuditRuleMockHandler(),
    getScanAuditRuleMockHandler(),
    getListAuditNonConformitiesMockHandler(),
    getSetAuditWaiverMockHandler(),
    getDeleteAuditNonConformityMockHandler(),
    getBatchSetAuditWaiverMockHandler(),
    getBatchDeleteAuditNonConformitiesMockHandler(),
];
