// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateGenreRequest,
  CreateGenreResponse,
  ListGenresResponse
} from '../model';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';






export type listGenresResponse200TextPlain = {
  data: ListGenresResponse
  status: 200
}

export type listGenresResponse200ApplicationJson = {
  data: ListGenresResponse
  status: 200
}

export type listGenresResponse200TextJson = {
  data: ListGenresResponse
  status: 200
}

export type listGenresResponseSuccess = (listGenresResponse200TextPlain | listGenresResponse200ApplicationJson | listGenresResponse200TextJson) & {
  headers: Headers;
};
;

export type listGenresResponse = (listGenresResponseSuccess)

export const getListGenresUrl = () => {




  return `/api/genres`
}

export const listGenres = async ( options?: RequestInit): Promise<listGenresResponse> => {

  const res = await fetch(getListGenresUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listGenresResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as listGenresResponse
}





export const getListGenresQueryKey = () => {
    return [
    'api','genres'
    ] as const;
    }


export const getListGenresQueryOptions = <TData = Awaited<ReturnType<typeof listGenres>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenres>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGenresQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGenres>>> = ({ signal }) => listGenres({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGenres>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGenresQueryResult = NonNullable<Awaited<ReturnType<typeof listGenres>>>
export type ListGenresQueryError = unknown


export function useListGenres<TData = Awaited<ReturnType<typeof listGenres>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenres>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGenres>>,
          TError,
          Awaited<ReturnType<typeof listGenres>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGenres<TData = Awaited<ReturnType<typeof listGenres>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenres>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGenres>>,
          TError,
          Awaited<ReturnType<typeof listGenres>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGenres<TData = Awaited<ReturnType<typeof listGenres>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenres>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListGenres<TData = Awaited<ReturnType<typeof listGenres>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGenres>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGenresQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}


export const invalidateListGenres = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getListGenresQueryKey() }, options);

  return queryClient;
}




export type createGenreResponse200TextPlain = {
  data: CreateGenreResponse
  status: 200
}

export type createGenreResponse200ApplicationJson = {
  data: CreateGenreResponse
  status: 200
}

export type createGenreResponse200TextJson = {
  data: CreateGenreResponse
  status: 200
}

export type createGenreResponseSuccess = (createGenreResponse200TextPlain | createGenreResponse200ApplicationJson | createGenreResponse200TextJson) & {
  headers: Headers;
};
;

export type createGenreResponse = (createGenreResponseSuccess)

export const getCreateGenreUrl = () => {




  return `/api/genres`
}

export const createGenre = async (createGenreRequest: CreateGenreRequest, options?: RequestInit): Promise<createGenreResponse> => {

  const res = await fetch(getCreateGenreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createGenreRequest,)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createGenreResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as createGenreResponse
}




export const getCreateGenreMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGenre>>, TError,{data: CreateGenreRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createGenre>>, TError,{data: CreateGenreRequest}, TContext> => {

const mutationKey = ['createGenre'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGenre>>, {data: CreateGenreRequest}> = (props) => {
          const {data} = props ?? {};

          return  createGenre(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGenreMutationResult = NonNullable<Awaited<ReturnType<typeof createGenre>>>
    export type CreateGenreMutationBody = CreateGenreRequest
    export type CreateGenreMutationError = unknown

    export const useCreateGenre = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGenre>>, TError,{data: CreateGenreRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGenre>>,
        TError,
        {data: CreateGenreRequest},
        TContext
      > => {
      return useMutation(getCreateGenreMutationOptions(options), queryClient);
    }


export const getListGenresResponseMock = (overrideResponse: Partial<Extract<ListGenresResponse, object>> = {}): ListGenresResponse => (faker.helpers.arrayElement([{genres: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}}), songsCount: faker.helpers.arrayElement([faker.number.int(), undefined])})), ...overrideResponse}, {genres: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}}), songsCount: faker.helpers.arrayElement([faker.number.int(), undefined])})), ...overrideResponse}, {genres: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}}), songsCount: faker.helpers.arrayElement([faker.number.int(), undefined])})), ...overrideResponse}]))

export const getCreateGenreResponseMock = (overrideResponse: Partial<Extract<CreateGenreResponse, object>> = {}): CreateGenreResponse => (faker.helpers.arrayElement([{genre: {id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse}, {genre: {id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse}, {genre: {id: faker.number.int(), name: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse}]))


export const getListGenresMockHandler = (overrideResponse?: ListGenresResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ListGenresResponse> | ListGenresResponse), options?: RequestHandlerOptions) => {
  return http.get('*/genres', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListGenresResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateGenreMockHandler = (overrideResponse?: CreateGenreResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateGenreResponse> | CreateGenreResponse), options?: RequestHandlerOptions) => {
  return http.post('*/genres', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateGenreResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGenresMock = () => [
  getListGenresMockHandler(),
  getCreateGenreMockHandler()
]
