// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */

import {faker} from "@faker-js/faker";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    InvalidateOptions,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";
import {useMutation, useQuery} from "@tanstack/react-query";
import type {RequestHandlerOptions} from "msw";
import {http, HttpResponse} from "msw";
import type {
    CreatePlayHistoryRequest,
    CreatePlayHistoryResponse,
    ListPlayHistoryParams,
    ListPlayHistoryResponse,
} from "../model";

export type recordPlayHistoryResponse200 = {
    data: CreatePlayHistoryResponse;
    status: 200;
};

export type recordPlayHistoryResponseSuccess = recordPlayHistoryResponse200 & {
    headers: Headers;
};

export type recordPlayHistoryResponse = recordPlayHistoryResponseSuccess;

export const getRecordPlayHistoryUrl = () => {
    return `/api/play-history`;
};

export const recordPlayHistory = async (
    createPlayHistoryRequest: CreatePlayHistoryRequest,
    options?: RequestInit,
): Promise<recordPlayHistoryResponse> => {
    const res = await fetch(getRecordPlayHistoryUrl(), {
        ...options,
        method: "POST",
        headers: {"Content-Type": "application/json", ...options?.headers},
        body: JSON.stringify(createPlayHistoryRequest),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: recordPlayHistoryResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as recordPlayHistoryResponse;
};

export const getRecordPlayHistoryMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof recordPlayHistory>>,
        TError,
        { data: CreatePlayHistoryRequest },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof recordPlayHistory>>,
    TError,
    { data: CreatePlayHistoryRequest },
    TContext
> => {
    const mutationKey = ["recordPlayHistory"];
    const {mutation: mutationOptions, fetch: fetchOptions} = options
        ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
            ? options
            : {...options, mutation: {...options.mutation, mutationKey}}
        : {mutation: {mutationKey}, fetch: undefined};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof recordPlayHistory>>,
        { data: CreatePlayHistoryRequest }
    > = (props) => {
        const {data} = props ?? {};

        return recordPlayHistory(data, fetchOptions);
    };

    return {mutationFn, ...mutationOptions};
};

export type RecordPlayHistoryMutationResult = NonNullable<
    Awaited<ReturnType<typeof recordPlayHistory>>
>;
export type RecordPlayHistoryMutationBody = CreatePlayHistoryRequest;
export type RecordPlayHistoryMutationError = unknown;

export const useRecordPlayHistory = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof recordPlayHistory>>,
            TError,
            { data: CreatePlayHistoryRequest },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof recordPlayHistory>>,
    TError,
    { data: CreatePlayHistoryRequest },
    TContext
> => {
    return useMutation(getRecordPlayHistoryMutationOptions(options), queryClient);
};
export type listPlayHistoryResponse200 = {
    data: ListPlayHistoryResponse;
    status: 200;
};

export type listPlayHistoryResponseSuccess = listPlayHistoryResponse200 & {
    headers: Headers;
};

export type listPlayHistoryResponse = listPlayHistoryResponseSuccess;

export const getListPlayHistoryUrl = (params?: ListPlayHistoryParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/play-history?${stringifiedParams}`
        : `/api/play-history`;
};

export const listPlayHistory = async (
    params?: ListPlayHistoryParams,
    options?: RequestInit,
): Promise<listPlayHistoryResponse> => {
    const res = await fetch(getListPlayHistoryUrl(params), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: listPlayHistoryResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as listPlayHistoryResponse;
};

export const getListPlayHistoryQueryKey = (params?: ListPlayHistoryParams) => {
    return ["api", "play-history", ...(params ? [params] : [])] as const;
};

export const getListPlayHistoryQueryOptions = <
    TData = Awaited<ReturnType<typeof listPlayHistory>>,
    TError = unknown,
>(
    params?: ListPlayHistoryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPlayHistory>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
) => {
    const {query: queryOptions, fetch: fetchOptions} = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListPlayHistoryQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlayHistory>>> = ({
                                                                                     signal,
                                                                                 }) => listPlayHistory(params, {signal, ...fetchOptions});

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof listPlayHistory>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPlayHistoryQueryResult = NonNullable<
    Awaited<ReturnType<typeof listPlayHistory>>
>;
export type ListPlayHistoryQueryError = unknown;

export function useListPlayHistory<
    TData = Awaited<ReturnType<typeof listPlayHistory>>,
    TError = unknown,
>(
    params: undefined | ListPlayHistoryParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPlayHistory>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listPlayHistory>>,
                    TError,
                    Awaited<ReturnType<typeof listPlayHistory>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPlayHistory<
    TData = Awaited<ReturnType<typeof listPlayHistory>>,
    TError = unknown,
>(
    params?: ListPlayHistoryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPlayHistory>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listPlayHistory>>,
                    TError,
                    Awaited<ReturnType<typeof listPlayHistory>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPlayHistory<
    TData = Awaited<ReturnType<typeof listPlayHistory>>,
    TError = unknown,
>(
    params?: ListPlayHistoryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPlayHistory>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useListPlayHistory<
    TData = Awaited<ReturnType<typeof listPlayHistory>>,
    TError = unknown,
>(
    params?: ListPlayHistoryParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPlayHistory>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListPlayHistoryQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return {...query, queryKey: queryOptions.queryKey};
}

export const invalidateListPlayHistory = async (
    queryClient: QueryClient,
    params?: ListPlayHistoryParams,
    options?: InvalidateOptions,
): Promise<QueryClient> => {
    await queryClient.invalidateQueries(
        {queryKey: getListPlayHistoryQueryKey(params)},
        options,
    );

    return queryClient;
};

export const getRecordPlayHistoryResponseMock = (
    overrideResponse: Partial<CreatePlayHistoryResponse> = {},
): CreatePlayHistoryResponse => ({
    created: faker.datatype.boolean(),
    id: faker.number.int({min: undefined, max: undefined}),
    songPlayCount: faker.number.int({min: undefined, max: undefined}),
    ...overrideResponse,
});

export const getListPlayHistoryResponseMock = (
    overrideResponse: Partial<ListPlayHistoryResponse> = {},
): ListPlayHistoryResponse => ({
    items: Array.from(
        {length: faker.number.int({min: 1, max: 10})},
        (_, i) => i + 1,
    ).map(() => ({
        id: faker.number.int({min: undefined, max: undefined}),
        songId: faker.number.int({min: undefined, max: undefined}),
        songTitle: faker.string.alpha({length: {min: 10, max: 20}}),
        albumId: faker.number.int({min: undefined, max: undefined}),
        albumName: faker.string.alpha({length: {min: 10, max: 20}}),
        coverId: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
                faker.number.int({min: undefined, max: undefined}),
                null,
            ]),
            undefined,
        ]),
        artistId: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
                faker.number.int({min: undefined, max: undefined}),
                null,
            ]),
            undefined,
        ]),
        artistName: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
                faker.string.alpha({length: {min: 10, max: 20}}),
                null,
            ]),
            undefined,
        ]),
        deviceId: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
                faker.number.int({min: undefined, max: undefined}),
                null,
            ]),
            undefined,
        ]),
        deviceName: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
                faker.string.alpha({length: {min: 10, max: 20}}),
                null,
            ]),
            undefined,
        ]),
        playedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
    })),
    ...overrideResponse,
});

export const getRecordPlayHistoryMockHandler = (
    overrideResponse?:
        | CreatePlayHistoryResponse
        | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
    ) => Promise<CreatePlayHistoryResponse> | CreatePlayHistoryResponse),
    options?: RequestHandlerOptions,
) => {
    return http.post(
        "*/play-history",
        async (info) => {
            return new HttpResponse(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getRecordPlayHistoryResponseMock(),
                {status: 200, headers: {"Content-Type": "text/plain"}},
            );
        },
        options,
    );
};

export const getListPlayHistoryMockHandler = (
    overrideResponse?:
        | ListPlayHistoryResponse
        | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<ListPlayHistoryResponse> | ListPlayHistoryResponse),
    options?: RequestHandlerOptions,
) => {
    return http.get(
        "*/play-history",
        async (info) => {
            return new HttpResponse(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getListPlayHistoryResponseMock(),
                {status: 200, headers: {"Content-Type": "text/plain"}},
            );
        },
        options,
    );
};
export const getPlayHistoryMock = () => [
    getRecordPlayHistoryMockHandler(),
    getListPlayHistoryMockHandler(),
];
