/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs.index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'

const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SongsRoute,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlbumsRoute,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => SongsRoute,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/$artistId',
  path: '/$artistId',
  getParentRoute: () => ArtistsRoute,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AlbumsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/player': typeof PlayerRoute
  '/purchases': typeof PurchasesRoute
  '/songs': typeof SongsRouteWithChildren
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/songs/': typeof SongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player': typeof PlayerRoute
  '/purchases': typeof PurchasesRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/songs': typeof SongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/player': typeof PlayerRoute
  '/purchases': typeof PurchasesRoute
  '/songs': typeof SongsRouteWithChildren
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/songs/': typeof SongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/artists'
    | '/player'
    | '/purchases'
    | '/songs'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/songs/$songId'
    | '/albums/'
    | '/artists/'
    | '/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/player'
    | '/purchases'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/songs/$songId'
    | '/albums'
    | '/artists'
    | '/songs'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/artists'
    | '/player'
    | '/purchases'
    | '/songs'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/songs/$songId'
    | '/albums/'
    | '/artists/'
    | '/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRouteWithChildren
  ArtistsRoute: typeof ArtistsRouteWithChildren
  PlayerRoute: typeof PlayerRoute
  PurchasesRoute: typeof PurchasesRoute
  SongsRoute: typeof SongsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof SongsRoute
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/albums/': {
      id: '/albums/'
      path: '/'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof AlbumsRoute
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof SongsRoute
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof AlbumsRoute
    }
  }
}

interface AlbumsRouteChildren {
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
}

const AlbumsRouteChildren: AlbumsRouteChildren = {
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
}

const AlbumsRouteWithChildren =
  AlbumsRoute._addFileChildren(AlbumsRouteChildren)

interface ArtistsRouteChildren {
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface SongsRouteChildren {
  SongsSongIdRoute: typeof SongsSongIdRoute
  SongsIndexRoute: typeof SongsIndexRoute
}

const SongsRouteChildren: SongsRouteChildren = {
  SongsSongIdRoute: SongsSongIdRoute,
  SongsIndexRoute: SongsIndexRoute,
}

const SongsRouteWithChildren = SongsRoute._addFileChildren(SongsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRouteWithChildren,
  ArtistsRoute: ArtistsRouteWithChildren,
  PlayerRoute: PlayerRoute,
  PurchasesRoute: PurchasesRoute,
  SongsRoute: SongsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
