<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" />
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyMusic.Common\MyMusic.Common.csproj" />
      <ProjectReference Include="..\MyMusic.OpenTelemetry.XUnit\MyMusic.OpenTelemetry.XUnit.csproj" />
      <ProjectReference Include="..\MyMusic.Server\MyMusic.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\251progressie.mp3" />
      <EmbeddedResource Include="Resources\251progressie.mp3" />
    </ItemGroup>

</Project>
