plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.mymusic.xxhash'
version = '1.0.0'

def reactNativeArchitectures() {
  def value = project.getProperties().get("reactNativeArchitectures")
  return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

android {
  if (rootProject.hasProperty("ndkPath")) {
    ndkPath rootProject.ext.ndkPath
  }
  if (rootProject.hasProperty("ndkVersion")) {
    ndkVersion rootProject.ext.ndkVersion
  }

  namespace "com.mymusic.xxhash"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"

    externalNativeBuild {
      cmake {
        abiFilters(*reactNativeArchitectures())
        arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
      }
    }
  }

  externalNativeBuild {
    cmake {
      path "CMakeLists.txt"
    }
  }
}
