// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/ import type { AddToQueuePosition } from "./addToQueuePosition";

export interface AddToQueueRequest {
	songIds: number[];
	position?: AddToQueuePosition;
}
