// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/ import type { MetadataDiff } from "./metadataDiff";

export interface AutoFetchedMetadataResponse {
	hasMetadata: boolean;
	metadata?: null | MetadataDiff;
	/** @nullable */
	fetchedAt?: string | null;
	/** @nullable */
	sourceName?: string | null;
	preSelectedFields?: string[];
}
