// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
export interface CreatePlayHistoryRequest {
    songId: number;
    clientId: string;
    /** @nullable */
    deviceId?: number | null;
}
