/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {CreateUserItem} from "./createUserItem";

export interface CreateUserResponse2 {
    user: CreateUserItem;
}
