/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {CreateDeviceItem} from "./createDeviceItem";

export interface CreateDeviceResponse {
    device: CreateDeviceItem;
}
