// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
export interface CreateUserItem {
    id: number;
    username: string;
    name: string;
    colorScheme: string;
}
