/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {PurchasedSongStatus} from "./purchasedSongStatus";

export interface DeletePurchaseItem {
    id: number;
    sourceId: number;
    sourceName: string;
    sourceIcon: string;
    userId: number;
    externalId: string;
    /** @nullable */
    cover?: string | null;
    title: string;
    subTitle: string;
    status: PurchasedSongStatus;
    progress: number;
    /** @nullable */
    songId?: number | null;
    /** @nullable */
    errorMessage: string | null;
    createdAt: string;
}
