// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/
export interface DeviceSongRef {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id: number;
	path: string;
	/** @nullable */
	syncAction?: string | null;
}
