// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { ListSongItem } from './listSongItem';

export interface ExcludedPairItem {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number;
  songA: ListSongItem;
  songB: ListSongItem;
  createdAt: string;
  /** @nullable */
  reason?: string | null;
}
