// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
export type GetArtistFilterValuesParams = {
    field?: string;
    search?: string;
    limit?: number;
};
