/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {GetArtistResponseGenre} from "./getArtistResponseGenre";
import type {GetArtistResponseSongAlbum} from "./getArtistResponseSongAlbum";
import type {GetArtistResponseSongArtist} from "./getArtistResponseSongArtist";

export interface GetArtistResponseSong {
    id: number;
    /** @nullable */
    cover: number | null;
    title: string;
    artists: GetArtistResponseSongArtist[];
    album: GetArtistResponseSongAlbum;
    genres: GetArtistResponseGenre[];
    /** @nullable */
    year: number | null;
    duration: string;
    isFavorite: boolean;
    isExplicit: boolean;
}
