/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {GetAlbumResponseSong} from "./getAlbumResponseSong";

export interface GetAlbumResponseAlbum {
    id: number;
    /** @nullable */
    cover: number | null;
    name: string;
    /** @nullable */
    year: number | null;
    artistId: number;
    artistName: string;
    songsCount: number;
    createdAt: string;
    songs: GetAlbumResponseSong[];
}
