/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */

import type {ListSongsAlbum} from "./listSongsAlbum";
import type {ListSongsArtist} from "./listSongsArtist";
import type {ListSongsGenre} from "./listSongsGenre";

export interface GetPlaylistSong {
    rank: number;
    order: number;
    id: number;
    /** @nullable */
    cover: number | null;
    title: string;
    artists: ListSongsArtist[];
    album: ListSongsAlbum;
    genres: ListSongsGenre[];
    /** @nullable */
    year: number | null;
    duration: string;
    isFavorite: boolean;
    isExplicit: boolean;
}
