/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {GetPlaylistSong} from "./getPlaylistSong";
import type {PlaylistType} from "./playlistType";

export interface GetPlaylistItem {
    id: number;
    name: string;
    type: PlaylistType;
    /** @nullable */
    currentSongId?: number | null;
    songs: GetPlaylistSong[];
}
