// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/ import type { ListSongsAlbum } from "./listSongsAlbum";
import type { ListSongsArtist } from "./listSongsArtist";
import type { ListSongsGenre } from "./listSongsGenre";

export interface GetPlaylistSong {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	order: number;
	/** @nullable */
	addedAtPlaylist?: string | null;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id: number;
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	cover: number | null;
	title: string;
	artists: ListSongsArtist[];
	album: ListSongsAlbum;
	genres: ListSongsGenre[];
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	year: number | null;
	duration: string;
	isFavorite: boolean;
	isExplicit: boolean;
	createdAt: string;
	/** @nullable */
	addedAt?: string | null;
}
