// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
import type {GetSongResponseAlbumArtist} from "./getSongResponseAlbumArtist";

export interface GetSongResponseAlbum {
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    id: number;
    name: string;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    year: number | null;
    artist?: null | GetSongResponseAlbumArtist;
}
