/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {GetSongResponseAlbum} from "./getSongResponseAlbum";
import type {GetSongResponseArtist} from "./getSongResponseArtist";
import type {GetSongResponseDevice} from "./getSongResponseDevice";
import type {GetSongResponseGenre} from "./getSongResponseGenre";

export interface GetSongResponseSong {
    id: number;
    /** @nullable */
    cover: number | null;
    title: string;
    label: string;
    artists: GetSongResponseArtist[];
    album: GetSongResponseAlbum;
    genres: GetSongResponseGenre[];
    devices: GetSongResponseDevice[];
    /** @nullable */
    year: number | null;
    duration: string;
    isFavorite: boolean;
    isExplicit: boolean;
    createdAt: string;
    /** @nullable */
    addedAt?: string | null;
    /** @nullable */
    lyrics?: string | null;
}
