// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { SecondarySongAction } from './secondarySongAction';

export interface GroupResolution {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  nonConformityId?: number | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  primarySongId: number;
  secondaryActions: SecondarySongAction[];
}
