/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ListPlaylistItem {
    id: number;
    name: string;
    songCount: number;
    createdAt: string;
    /** @nullable */
    modifiedAt?: string | null;
}
