// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
import type {ListSourcesItem} from "./listSourcesItem";

export interface ListSourcesResponse {
    sources: ListSourcesItem[];
}
