// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
export interface ListAlbumsItem {
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    id: number;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    cover: number | null;
    name: string;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    year: number | null;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    songsCount: number | null;
    createdAt: string;
}
