// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { SoundalikeSongItem } from './soundalikeSongItem';

export interface MatchSoundalikesResponse {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  matchScore: number | null;
  songs: SoundalikeSongItem[];
}
