// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/ import type { MetadataAlbum } from "./metadataAlbum";

export interface MetadataFieldOfMetadataAlbum {
	old: null | MetadataAlbum;
	new: null | MetadataAlbum;
}
