// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
import type {PlaylistAction} from "./playlistAction";

export interface PlaylistSongAction {
    playlistId: number;
    action: PlaylistAction;
}
