// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/
export interface PreviewDeviceNamingTemplateError {
  message: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  line: number;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  column: number;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  endLine: number;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  endColumn: number;
}
