// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { QuerySongDevicesDevice } from './querySongDevicesDevice';
import type { QuerySongDevicesSong } from './querySongDevicesSong';

export interface QuerySongDevicesResponse {
  songs: QuerySongDevicesSong[];
  devices: QuerySongDevicesDevice[];
}
