// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/
export interface ReplaceSongFileResponse {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number;
  repositoryPath: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  size: number;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  duration: number;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  bitrate?: number | null;
}
