// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { StructValueUpdateOfboolean } from './structValueUpdateOfboolean';
import type { StructValueUpdateOfdecimal } from './structValueUpdateOfdecimal';
import type { StructValueUpdateOfint } from './structValueUpdateOfint';
import type { ValueUpdateOfAlbumRef } from './valueUpdateOfAlbumRef';
import type { ValueUpdateOfArtworkRef } from './valueUpdateOfArtworkRef';
import type { ValueUpdateOfListOfArtistRef } from './valueUpdateOfListOfArtistRef';
import type { ValueUpdateOfListOfGenreRef } from './valueUpdateOfListOfGenreRef';
import type { ValueUpdateOfstring } from './valueUpdateOfstring';

export interface SongMultiUpdateItem {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  songId: number;
  title?: null | ValueUpdateOfstring;
  year?: null | StructValueUpdateOfint;
  lyrics?: null | ValueUpdateOfstring;
  rating?: null | StructValueUpdateOfdecimal;
  explicit?: null | StructValueUpdateOfboolean;
  cover?: null | ValueUpdateOfArtworkRef;
  album?: null | ValueUpdateOfAlbumRef;
  artists?: null | ValueUpdateOfListOfArtistRef;
  genres?: null | ValueUpdateOfListOfGenreRef;
}
