/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SongDeviceItem {
    deviceId: number;
    deviceName: string;
    /** @nullable */
    deviceIcon?: string | null;
    /** @nullable */
    deviceColor?: string | null;
    /** @nullable */
    path?: string | null;
    /** @nullable */
    syncAction?: string | null;
}
