// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/
export interface SongMetadataFieldOfint {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	old: number;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	new: number;
}
