// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { SongHistoryDiffMetadata } from './songHistoryDiffMetadata';

export interface SongHistoryDiffResponse {
  metadata: SongHistoryDiffMetadata;
  /** @nullable */
  oldVersionDate?: string | null;
  newVersionDate: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  oldRevision?: number | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  newRevision: number;
}
