// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
import type {SourceArtwork} from "./sourceArtwork";
import type {SourceSongAlbum} from "./sourceSongAlbum";
import type {SourceSongArtist} from "./sourceSongArtist";

export interface SourceSong {
    id: string;
    title: string;
    album?: SourceSongAlbum;
    cover?: null | SourceArtwork;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    year?: number | null;
    /** @nullable */
    lyrics?: string | null;
    explicit?: boolean;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    size?: number;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    track?: number | null;
    /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
    duration?: string;
    artists: SourceSongArtist[];
    genres: string[];
    /** @nullable */
    link?: string | null;
    /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
    price?: number;
    /** @nullable */
    searchableText?: string | null;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    durationSeconds?: number;
    /** @nullable */
    durationCategory?: string | null;
    hasLyrics?: boolean;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    artistCount?: number;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    genreCount?: number;
}
