/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SyncRecordRequestItem {
    filePath: string;
    action: string;
    /** @nullable */
    songId?: number | null;
    /** @nullable */
    errorMessage?: string | null;
    /** @nullable */
    source?: string | null;
    /** @nullable */
    reason?: string | null;
}
