// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/
export type SyncRecordAction = typeof SyncRecordAction[keyof typeof SyncRecordAction];


export const SyncRecordAction = {
  CreateRemote: 'CreateRemote',
  UpdateRemote: 'UpdateRemote',
  CreateLocal: 'CreateLocal',
  UpdateLocal: 'UpdateLocal',
  Delete: 'Delete',
  Link: 'Link',
  Unlink: 'Unlink',
  Rename: 'Rename',
  Skipped: 'Skipped',
  Conflict: 'Conflict',
  UpdateTimestamp: 'UpdateTimestamp',
  Error: 'Error',
} as const;
