// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/ import type { SyncFileInfoItem } from "./syncFileInfoItem";
import type { SyncPotentialConflictItem } from "./syncPotentialConflictItem";

export interface SyncCheckResponse {
	toCreate: SyncFileInfoItem[];
	toUpdate: SyncFileInfoItem[];
	potentialConflicts: SyncPotentialConflictItem[];
}
