// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { JsonElement } from './jsonElement';
import type { SyncRecordAction } from './syncRecordAction';
import type { SyncRecordSongInfo } from './syncRecordSongInfo';

export interface SyncRecordResponseItem {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number;
  filePath: string;
  action: SyncRecordAction;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  songId?: number | null;
  data?: null | JsonElement;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  resolvesConflictRecordId?: number | null;
  songInfo?: null | SyncRecordSongInfo;
  /** @nullable */
  reason?: string | null;
  acknowledged?: boolean;
  processedAt?: string;
}
