/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */
import type {SyncRecordAction} from "./syncRecordAction";
import type {SyncRecordSource} from "./syncRecordSource";

export interface SyncRecordResponseItem {
    filePath: string;
    action: SyncRecordAction;
    source: SyncRecordSource;
    /** @nullable */
    songId?: number | null;
    /** @nullable */
    errorMessage?: string | null;
    /** @nullable */
    reason?: string | null;
    processedAt?: string;
}
