// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/ import type { UpdateSongAlbumArtist } from "./updateSongAlbumArtist";

export interface UpdateSongAlbum {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	id: number;
	name: string;
	artist?: null | UpdateSongAlbumArtist;
}
