// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/ import type { UpdateSourceData } from "./updateSourceData";

export interface UpdateSourceRequest {
	source: UpdateSourceData;
}
