// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { SongDevicePathItem } from './songDevicePathItem';
import type { SongDeviceUpdateItem } from './songDeviceUpdateItem';

export interface UpdateSongDevicesRequest {
  songIds: number[];
  updates: SongDeviceUpdateItem[];
  /** @nullable */
  paths?: SongDevicePathItem[] | null;
}
