// @ts-nocheck
/**
 Generated by orval 🍺
 Do not edit manually.
 MyMusic.Server | v1
 OpenAPI spec version: 1.0.0
 */
import type {UpdateSongAlbum} from "./updateSongAlbum";
import type {UpdateSongArtist} from "./updateSongArtist";
import type {UpdateSongGenre} from "./updateSongGenre";

/**
 * @nullable
 */
export type UpdateSongItem = {
    id: number;
    title: string;
    label: string;
    /** @nullable */
    cover: number | null;
    /** @nullable */
    year: number | null;
    /** @nullable */
    lyrics?: string | null;
    /** @nullable */
    rating?: number | null;
    explicit?: boolean;
    artists: UpdateSongArtist[];
    album: UpdateSongAlbum;
    genres: UpdateSongGenre[];
    /** @nullable */
    repositoryPath?: string | null;
} | null;
