/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MyMusic.Server | v1
 * OpenAPI spec version: 1.0.0
 */

export interface WeatherForecast {
	date?: string;
	temperatureC?: number;
	temperatureF?: number;
	/** @nullable */
	summary?: string | null;
}
