// @ts-nocheck
/**
Generated by orval 🍺
Do not edit manually.
MyMusic.Server | v1
OpenAPI spec version: 1.0.0
*/import type { WishlistItemStatus } from './wishlistItemStatus';
import type { WishlistSource } from './wishlistSource';

export interface WishlistItem {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  sourceId: number;
  query: string;
  /** @nullable */
  filter?: string | null;
  status: WishlistItemStatus;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  continuousFailedCount: number;
  /** @nullable */
  lastErrorMessage: string | null;
  createdAt: string;
  updatedAt: string;
  source: WishlistSource;
}
