// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMusic.Common;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyMusic.Common.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    partial class MusicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyMusic.Common.Entities.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArtistId")
                        .HasColumnType("bigint")
                        .HasColumnName("artist_id");

                    b.Property<long?>("CoverId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<int>("SongsCount")
                        .HasColumnType("integer")
                        .HasColumnName("songs_count");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_albums_artist_id");

                    b.HasIndex("CoverId")
                        .HasDatabaseName("ix_albums_cover_id");

                    b.HasIndex("OwnerId", "ArtistId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_albums_owner_id_artist_id_name");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.AlbumSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint")
                        .HasColumnName("album_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("SongsCount")
                        .HasColumnType("integer")
                        .HasColumnName("songs_count");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_album_sources");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_album_sources_album_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_album_sources_source_id");

                    b.ToTable("album_sources", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AlbumsCount")
                        .HasColumnType("integer")
                        .HasColumnName("albums_count");

                    b.Property<long?>("BackgroundId")
                        .HasColumnType("bigint")
                        .HasColumnName("background_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<long?>("PhotoId")
                        .HasColumnType("bigint")
                        .HasColumnName("photo_id");

                    b.Property<int>("SongsCount")
                        .HasColumnType("integer")
                        .HasColumnName("songs_count");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("BackgroundId")
                        .HasDatabaseName("ix_artists_background_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_artists_owner_id");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_artists_photo_id");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.ArtistSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArtistId")
                        .HasColumnType("bigint")
                        .HasColumnName("artist_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_artist_sources");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_artist_sources_artist_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_artist_sources_source_id");

                    b.ToTable("artist_sources", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Artwork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("mime_type");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_artworks");

                    b.ToTable("artworks", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NamingTemplate")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("naming_template");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_owner_id_name");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.DeviceSyncSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dry_run");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_device_sync_sessions");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_sync_sessions_device_id");

                    b.ToTable("device_sync_sessions", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.DeviceSyncSessionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("reason");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long?>("SongId")
                        .HasColumnType("bigint")
                        .HasColumnName("song_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_device_sync_session_records");

                    b.HasIndex("SessionId", "FilePath")
                        .IsUnique()
                        .HasDatabaseName("ix_device_sync_session_records_session_id_file_path");

                    b.ToTable("device_sync_session_records", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_owner_id_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Playlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_playlists");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_playlists_owner_id");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.PlaylistSong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<long>("PlaylistId")
                        .HasColumnType("bigint")
                        .HasColumnName("playlist_id");

                    b.Property<long>("SongId")
                        .HasColumnType("bigint")
                        .HasColumnName("song_id");

                    b.HasKey("Id")
                        .HasName("pk_playlist_songs");

                    b.HasIndex("PlaylistId")
                        .HasDatabaseName("ix_playlist_songs_playlist_id");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_playlist_songs_song_id");

                    b.ToTable("playlist_songs", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.PurchasedSong", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cover")
                        .HasColumnType("text")
                        .HasColumnName("cover");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<long?>("SongId")
                        .HasColumnType("bigint")
                        .HasColumnName("song_id");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sub_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_purchased_songs");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_purchased_songs_song_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_purchased_songs_source_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_purchased_songs_user_id");

                    b.ToTable("purchased_songs", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Song", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint")
                        .HasColumnName("album_id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("checksum");

                    b.Property<string>("ChecksumAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_algorithm");

                    b.Property<long?>("CoverId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("Explicit")
                        .HasColumnType("boolean")
                        .HasColumnName("explicit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<string>("Lyrics")
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("lyrics");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("repository_path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int?>("Track")
                        .HasColumnType("integer")
                        .HasColumnName("track");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_songs");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_songs_album_id");

                    b.HasIndex("CoverId")
                        .HasDatabaseName("ix_songs_cover_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_songs_owner_id");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongArtist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArtistId")
                        .HasColumnType("bigint")
                        .HasColumnName("artist_id");

                    b.Property<long>("SongId")
                        .HasColumnType("bigint")
                        .HasColumnName("song_id");

                    b.HasKey("Id")
                        .HasName("pk_song_artists");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_song_artists_artist_id");

                    b.HasIndex("SongId", "ArtistId")
                        .IsUnique()
                        .HasDatabaseName("ix_song_artists_song_id_artist_id");

                    b.ToTable("song_artists", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("DevicePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("device_path");

                    b.Property<DateTime>("LastSyncedModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_modified_at");

                    b.Property<long>("SongId")
                        .HasColumnType("bigint")
                        .HasColumnName("song_id");

                    b.Property<int?>("SyncAction")
                        .HasColumnType("integer")
                        .HasColumnName("sync_action");

                    b.HasKey("Id")
                        .HasName("pk_song_devices");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_song_devices_song_id");

                    b.HasIndex("DeviceId", "DevicePath")
                        .IsUnique()
                        .HasDatabaseName("ix_song_devices_device_id_device_path");

                    b.ToTable("song_devices", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongGenre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint")
                        .HasColumnName("genre_id");

                    b.Property<long>("SongId")
                        .HasColumnType("bigint")
                        .HasColumnName("song_id");

                    b.HasKey("Id")
                        .HasName("pk_song_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_song_genres_genre_id");

                    b.HasIndex("SongId", "GenreId")
                        .IsUnique()
                        .HasDatabaseName("ix_song_genres_song_id_genre_id");

                    b.ToTable("song_genres", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("SongId")
                        .HasColumnType("bigint")
                        .HasColumnName("song_id");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_song_sources");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_song_sources_song_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_song_sources_source_id");

                    b.ToTable("song_sources", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Source", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("address");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Album", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_artists_artist_id");

                    b.HasOne("MyMusic.Common.Entities.Artwork", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverId")
                        .HasConstraintName("fk_albums_artworks_cover_id");

                    b.HasOne("MyMusic.Common.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_users_owner_id");

                    b.Navigation("Artist");

                    b.Navigation("Cover");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.AlbumSource", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Album", "Album")
                        .WithMany("Sources")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_sources_albums_album_id");

                    b.HasOne("MyMusic.Common.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_sources_sources_source_id");

                    b.Navigation("Album");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Artist", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Artwork", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .HasConstraintName("fk_artists_artworks_background_id");

                    b.HasOne("MyMusic.Common.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artists_users_owner_id");

                    b.HasOne("MyMusic.Common.Entities.Artwork", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .HasConstraintName("fk_artists_artworks_photo_id");

                    b.Navigation("Background");

                    b.Navigation("Owner");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.ArtistSource", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Artist", "Artist")
                        .WithMany("Sources")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_sources_artists_artist_id");

                    b.HasOne("MyMusic.Common.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_sources_sources_source_id");

                    b.Navigation("Artist");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Device", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.DeviceSyncSession", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_sync_sessions_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.DeviceSyncSessionRecord", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.DeviceSyncSession", "Session")
                        .WithMany("Records")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_sync_session_records_device_sync_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Genre", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_genres_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Playlist", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.PlaylistSong", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_songs_playlists_playlist_id");

                    b.HasOne("MyMusic.Common.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_songs_songs_song_id");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.PurchasedSong", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .HasConstraintName("fk_purchased_songs_songs_song_id");

                    b.HasOne("MyMusic.Common.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchased_songs_sources_source_id");

                    b.HasOne("MyMusic.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchased_songs_users_user_id");

                    b.Navigation("Song");

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Song", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_songs_albums_album_id");

                    b.HasOne("MyMusic.Common.Entities.Artwork", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverId")
                        .HasConstraintName("fk_songs_artworks_cover_id");

                    b.HasOne("MyMusic.Common.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_songs_users_owner_id");

                    b.Navigation("Album");

                    b.Navigation("Cover");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongArtist", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_artists_artists_artist_id");

                    b.HasOne("MyMusic.Common.Entities.Song", "Song")
                        .WithMany("Artists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_artists_songs_song_id");

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongDevice", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Device", "Device")
                        .WithMany("Songs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_devices_devices_device_id");

                    b.HasOne("MyMusic.Common.Entities.Song", "Song")
                        .WithMany("Devices")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_devices_songs_song_id");

                    b.Navigation("Device");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongGenre", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_genres_genres_genre_id");

                    b.HasOne("MyMusic.Common.Entities.Song", "Song")
                        .WithMany("Genres")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_genres_songs_song_id");

                    b.Navigation("Genre");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.SongSource", b =>
                {
                    b.HasOne("MyMusic.Common.Entities.Song", "Song")
                        .WithMany("Sources")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_sources_songs_song_id");

                    b.HasOne("MyMusic.Common.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_sources_sources_source_id");

                    b.Navigation("Song");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Album", b =>
                {
                    b.Navigation("Songs");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Songs");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Device", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.DeviceSyncSession", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("MyMusic.Common.Entities.Song", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Devices");

                    b.Navigation("Genres");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
